-- Room status columns are included in migration 0018 for fresh databases.
-- This migration is intentionally kept as a no-op so deployments that already
-- applied the consolidated schema do not fail on a duplicate ALTER TABLE.
